
#define INIT_MODULE(MODULE) \
int JLINK_##MODULE##_Init(); \
if (!JLINK_##MODULE##_Init()) return 0;

int JLINK_General_Init() {
    INIT_MODULE(GERENAL_BASE)
    INIT_MODULE(GERENAL_SystemControl)
    INIT_MODULE(GERENAL_FILE_IO)
    INIT_MODULE(GERENAL_CONFIGURATION)
    INIT_MODULE(GERENAL_DEVICE_SPECIFIC)
    INIT_MODULE(GERENAL_RESET)
    INIT_MODULE(GERENAL_DEBUGGING)
    INIT_MODULE(GERENAL_MEM)
    return 1;
}